### ISSUE TITLE
RHEL support

### ISSUE THREAD

**Issue by pegasd** [pegasd/puppet-incron#11]
@markasammut requested RHEL support for the module.

Relevant PR: #10.

For now, it seems like we only need to change service name from `incron` to `incrond` on non-Debian-based systems.

**Comment by pegasd** [comment]
Hey, @markasammut, could you please provide the output of `sudo facter -p os` from one of your systems? Preferably the most used version of RHEL for you.

**Comment by markasammut** [comment]
# facter os
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "RedHat",
  release => {
    full => "7.5",
    major => "7",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}

This though should apply also on CentOS hosts, so I'd use the OS Family not the OS name.

**Comment by pegasd** [comment]
Thanks, @markasammut !

Yes, good idea about the `os.family` part.

I just spun up a CentOS docker to get facter info from there.

on CentOS:
```
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "CentOS",
  release => {
    full => "7.6.1810",
    major => "7",
    minor => "6"
  },
  selinux => {
    enabled => false
  }
}
```

and on RedHat (re-posting):

```
{
  architecture => "x86_64",
  family => "RedHat",
  hardware => "x86_64",
  name => "RedHat",
  release => {
    full => "7.5",
    major => "7",
    minor => "5"
  },
  selinux => {
    enabled => false
  }
}
```

**Comment by pegasd** [comment]
Here's `hiera.yaml` from [puppetlabs-ntp](https://github.com/puppetlabs/puppetlabs-ntp):

```yaml
version: 5

defaults:
  datadir: 'data'
  data_hash: 'yaml_data'

hierarchy:
  - name: 'Full Version'
    path: '%{facts.os.name}-%{facts.os.release.full}.yaml'

  - name: 'Major Version'
    path: '%{facts.os.name}-%{facts.os.release.major}.yaml'

  - name: 'Distribution Name'
    path: '%{facts.os.name}.yaml'

  - name: 'Operating System Family'
    path: '%{facts.os.family}-family.yaml'

  - name: 'common'
    path: 'common.yaml'
```

Seems like for now we only need the `Operating System Family` bit.
